name: strathmore_visitor_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Core functionality
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  http: ^1.2.2 # Added for API calls

  # Database and media
  sqflite: ^2.4.2
  image_picker: ^1.1.2
  qr_code_scanner_plus: ^2.0.0
  qr_flutter: ^4.1.0
  permission_handler: ^12.0.1
  connectivity_plus: ^5.0.2 # or latest version
  image: ^4.5.4
  google_ml_kit: ^0.20.0
  flutter_typeahead: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/strathmore_logo.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700