name: strathmore_visitor_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Core functionality
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  http: ^1.2.2

  # Database and media
  sqflite: ^2.4.2
  image_picker: ^1.1.2
  qr_code_scanner_plus: ^2.0.0
  qr_flutter: ^4.1.0
  permission_handler: ^12.0.1
  connectivity_plus: ^5.0.2
  image: ^4.5.4
  google_ml_kit: ^0.20.0
  flutter_typeahead: ^5.2.0
  flutter_secure_storage: ^9.2.4
  liquid_swipe: ^3.1.0
  confetti: ^0.8.0
  im_stepper: ^1.0.1+1
  intl: ^0.20.2
  jwt_decoder: ^2.0.1
  animate_do: ^4.2.0
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/strathmore_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/strathmore_logo.png"
  adaptive_icon_foreground: "assets/images/strathmore_logo.png"
  adaptive_icon_background: "#ffffff"